[package]
name = "days_between"
version = "0.5.0"
authors = ["Charlie Saunders <charlieasaunders@gmail.com>"]
license = "MIT"

[dependencies]
chrono = "0.4"
clap ="~2.29"
regex = "0.2"

[dev-dependencies]
assert_cli = "0.5"
